[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["foundry-devops/=lib/foundry-devops"]
fs_permissions = [{ access = "read", path = "./src/Problems/" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
